version: '3'
services:
  app:
    image: php:7.4-apache
    environment:
      - MYSQLHOST=containers-us-west-45.railway.app
      - MYSQLUSER=root
      - MYSQLPASSWORD=cFaIcVJkdQmOVYwXTJYrODLUMweJIgNa
      - MYSQLDATABASE=railway
      - MYSQLPORT=3306
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
