version: "3.8"

services:
  app:
    container_name: mlbaunilha-erp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      PORT: 10000
      PHP_DISPLAY_ERRORS: "On"         # Altere para Off em produção
      PHP_ERROR_REPORTING: "E_ALL"
    volumes:
      - .:/var/www/html                # Para desenvolvimento local (opcional)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

