version: '3.8'

services:
  app:
    build: .
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: erp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
